<a href="https://colab.research.google.com/github/aayushkadahal/Data-Science-Learning/blob/main/Feature_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Titanic Dataset – Feature Encoding in Python

## Objective
This notebook demonstrates the essential feature encoding techniques used in data preprocessing for machine learning using the Titanic dataset.

## Workflow
- Import the required libraries
- Load and explore the dataset
- Identify categorical features
- Apply Label Encoding
- Apply One-Hot Encoding
- Apply Dummy Encoding
- Apply Ordinal Encoding
- Apply Frequency Encoding
- Apply Manual Mapping

**Dataset:** `Titanic-Dataset.csv`

**Libraries:** Pandas, NumPy, Scikit-learn

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import (
    LabelEncoder,
    OneHotEncoder,
    OrdinalEncoder
)

In [3]:
df = pd.read_csv("Titanic-Dataset.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

##Label Encoding(Sex)

In [5]:
label_df = df.copy()

le = LabelEncoder()
label_df["Sex"] = le.fit_transform(label_df["Sex"])

label_df[["Sex"]].head()

   Sex
0    1
1    0
2    0
3    0
4    1

In [6]:
onehot_df = pd.get_dummies(
    df,
    columns=["Embarked"],
    dtype=int
)

onehot_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,0,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,1,0,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,0,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,0,0,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,0,0,1

##One-Hot Encoding(Embarked)

In [7]:
onehot_df = pd.get_dummies(
    df,
    columns=["Embarked"],
    dtype=int
)

onehot_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,0,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,1,0,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,0,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,0,0,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,0,0,1

##Dummy Encoding

In [8]:
dummy_df = pd.get_dummies(
    df,
    columns=["Embarked"],
    drop_first=True,
    dtype=int
)

dummy_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,0,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,0,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,0,1

##Ordinal Encoding (Pclass)

In [9]:
ordinal_df = df.copy()

encoder = OrdinalEncoder(categories=[[1, 2, 3]])

ordinal_df["Pclass"] = encoder.fit_transform(
    ordinal_df[["Pclass"]]
)

ordinal_df[["Pclass"]].head()

   Pclass
0     2.0
1     0.0
2     2.0
3     0.0
4     2.0

##Frequency Encoding (Embarked)

In [10]:

freq_df = df.copy()

frequency = freq_df["Embarked"].value_counts()

freq_df["Embarked_Freq"] = freq_df["Embarked"].map(frequency)

freq_df[["Embarked", "Embarked_Freq"]].head()

  Embarked  Embarked_Freq
0        S          644.0
1        C          168.0
2        S          644.0
3        S          644.0
4        S          644.0

##Manual Mapping

In [11]:
map_df = df.copy()

sex_map = {
    "male": 1,
    "female": 0
}

map_df["Sex"] = map_df["Sex"].map(sex_map)

map_df[["Sex"]].head()

   Sex
0    1
1    0
2    0
3    0
4    1